name: nightly
on:
  push:
    branches: [main, master]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.job }}
  cancel-in-progress: true

jobs:
  nightly:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base: [debian, alpine]
    env:
      HEDGEDOC_VERSION: master
      HEDGEDOC_IMAGE: quay.io/hedgedoc/hedgedoc-nightly
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set date
        run: echo TODAY=$(date +%Y%m%d) >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Login to docker registry
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4
        with:
          registry: quay.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          file: ./${{ matrix.base }}/Dockerfile
          labels: quay.expires-after=1w
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            VERSION=${{ env.HEDGEDOC_VERSION }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.HEDGEDOC_IMAGE }}:${{ env.TODAY }}-${{ matrix.base }}
            ${{ env.HEDGEDOC_IMAGE }}:${{ matrix.base }}
